### ISSUE TITLE
JS file is not secure

### ISSUE THREAD

**Issue by purnendudash** [edu-sharing/moodle-assignsubmission_edusharing#2]
https://github.com/edu-sharing/moodle-assignsubmission_edusharing/blob/54c5ee14b446ef9f378b4b5540a270afaff16f37/locallib.php#L206

Via this javascript, its possible to add php check from client side and add php file on tmp folder.

Also js should be served via amd.

**Comment by zieglermarian** [comment]
Hello Purnendu,

thanks for the feedback! I moved all inline JS to a module.

**Comment by purnendudash** [comment]
But Cant we change the filetype via js check and upload php files on temp folder?
